MIPS: Loongson: Fix gpio.h
The following error is fixed:

  [snip]
  CHK     include/linux/version.h
  CHK     include/generated/utsrelease.h
  Checking missing-syscalls for N32
  CALL    scripts/checksyscalls.sh
  Checking missing-syscalls for O32
  CALL    scripts/checksyscalls.sh
  CALL    scripts/checksyscalls.sh
  CHK     include/generated/compile.h
  CC      drivers/staging/ath6kl/os/linux/ar6000_drv.o
In file included from arch/mips/include/asm/mach-loongson/gpio.h:16,
                 from drivers/staging/ath6kl/os/linux/include/ar6000_drv.h:55,
                 from drivers/staging/ath6kl/os/linux/ar6000_drv.c:29:
include/asm-generic/gpio.h: In function 'gpio_get_value_cansleep':
include/asm-generic/gpio.h:233: error: implicit declaration of function 'gpio_get_value'
include/asm-generic/gpio.h: In function 'gpio_set_value_cansleep':
include/asm-generic/gpio.h:239: error: implicit declaration of function 'gpio_set_value'
In file included from drivers/staging/ath6kl/os/linux/include/ar6000_drv.h:55,
                 from drivers/staging/ath6kl/os/linux/ar6000_drv.c:29:
arch/mips/include/asm/mach-loongson/gpio.h: At top level:
arch/mips/include/asm/mach-loongson/gpio.h:18: warning: conflicting types for 'gpio_set_value'
include/asm-generic/gpio.h:239: note: previous implicit declaration of 'gpio_set_value' was here
  [snip]

For gpio support is not necessary, we have removed the ARCH_WANT_GPIOLIB for
Loongson2, but the gpio.h still export the related functions, which may produce
the above building errors. This patch only export the functions for
CONFIG_GENERIC_GPIO(selected by GPIOLIB) and to allow the users to select
GPIOLIB, we select ARCH_WANT_OPTIONAL_GPIOLIB.

And also, ARCH_NR_GPIOS is defined and replaced STLS2F_N_GPIO.

Signed-off-by: Wu Zhangjin <wuzhangjin@gmail.com>